site_name: Grupo07

repo_name: "teste_gh_pages"
repo_url: "https://vitorb2002.github.io/teste_gh_pages/"

theme:
  name: material
  language: "pt"
  palette:
    primary: light green
    accent: white
  features:
    - navigation.tabs
  font:
    text: "Montserrat"
    code: "sans-serif"

nav:
  - Início: index.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
  - Atas de reunião:
    - Reunião 00: atas/reuniao-00.md
    - Reunião 01: atas/reuniao-01.md
  - Reuniões:
    - Reuniões: reunioes/reunioes.md

